name: HACS
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
jobs:
  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: HACS Validation
        uses: hacs/action@22.5.0
        with:
            category: integration
